### ISSUE TITLE
Not an issue but a question-I'm trying to run your nginx container extended with phpbb

### ISSUE THREAD

**Issue by SeppPenner** [MarvAmBass/docker-nginx-ssl-secure#6]
I'm trying to run the nginx ssl container with additionally phpBB installed. As you seem to be more experienced in writing Dockerfiles, could you maybe take a look at my project https://github.com/SeppPenner/docker-nginx-ssl-secure ? 

Thank you in advance :)

**Comment by MarvAmBass** [comment]
Hi there I'm not really working with PHP.

Maybe you can take a look at https://github.com/MarvAmBass/docker-nginx-ssl-php which uses this repository as parent. Maybe you find some hints there.

If not you should check how to install phpBB on a Debian system.

Kind regards.

**Comment by SeppPenner** [comment]
Hi @MarvAmBass,

I've found a solution here (The example runs phpBB in an Apache Server. However, it works now):

https://github.com/blueimp/phpbb/issues/1#issuecomment-372652367
